version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: rotation-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rotation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: >
      postgres
        -c shared_buffers=256MB
        -c max_connections=200
        -c effective_cache_size=1GB
        -c work_mem=16MB
        -c maintenance_work_mem=64MB
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c wal_buffers=16MB
        -c max_wal_size=2GB
        -c checkpoint_completion_target=0.9
        -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: